version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/wordpress/
file_exists_behavior: OVERWRITE
permissions:
  - object: /usr/share/nginx/wordpress
    pattern: "**"
    owner: nginx
    group: nginx
    mode: 755
    type:
      - file
  - object: /usr/share/nginx/wordpress
    pattern: "**"
    owner: nginx
    group: nginx
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop: 
    - location: scripts/applicationstop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root
