version: 0.2
env:
  secrets-manager:
    DB_USER: arn:aws:secretsmanager:ap-south-1:185633157927:secret:wordpress/host-huiY48:username
    DB_PASSWORD : arn:aws:secretsmanager:ap-south-1:185633157927:secret:wordpress/host-huiY48:password
    DB_HOST: arn:aws:secretsmanager:ap-south-1:185633157927:secret:wordpress/host-huiY48:host
    DB_NAME: arn:aws:secretsmanager:ap-south-1:185633157927:secret:wordpress/host-huiY48:database_name
phases:
  install:
    commands: 
      - yum install -y git 
      - yum install -y gettext
  pre_build: 
    commands:
      - export DB_NAME=$DB_NAME
      - export DB_USER=$DB_USER
      - export DB_PASS=$DB_PASSWORD
      - export DB_HOST=$DB_HOST
      - export table_prefix='$table_prefix'
  build:
    commands:
      #- git clone https://github.com/sumzzgit/wordpress.git
      - envsubst < wp-config-sample.php
      - envsubst < wp-config-sample.php >> wp-config.php
      - cat wp-config.php
      #- zip -r wordpress.zip .
      #- aws s3 cp wordpress.zip s3://sumzzbucket2/artifact/wordpress.zip
artifacts:
  files:
    - '**/*'
